const list = [
    {
      id: 1,
      title: "VOLLEY BALL",
      author: "3 BALL COMBO",
      price: 599,
      img: "https://tse1.mm.bing.net/th?id=OIP.DgdZIv814wGxm8_zH6MplAHaDn&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 2,
      title: "HOCKEY",
      author: "HOCKEY BAT AND BALL COMBO",
      price: 749,
      img: "https://cdn4.vectorstock.com/i/1000x1000/83/78/field-hockey-equipment-and-small-ball-vector-21278378.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "CRICKET",
      author: "CRICKET BAT AND BALL WITH STUMP COMBO",
      price: 1499,
      img: "https://tse1.mm.bing.net/th?id=OIP.uxoqB_GvdjrdLK5DCboaogHaHa&pid=Api&rs=1&c=1&qlt=95&w=119&h=119",
      amount: 1,
    },
    {
      id: 4,
      title: "BASKET BALL",
      author: "BASKET BALL WITH NET COMBO",
      price: 1999,
      img: "https://tse3.mm.bing.net/th?id=OIP.jM8lLCITtk9wn9eibKXRGQHaHa&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 5,
      title: "FOOTBALL",
      author: "BALL WITH GOAL POST COMBO",
      price: 4449,
      img: "https://tse2.mm.bing.net/th?id=OIP.MT7dToLZvnmx9RzU79ELWQHaHa&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 6,
      title: "BOXING",
      author: "1 GLOVES AND KIT BAG 36 INCH COMBO",
      price: 135,
      img: "https://tse1.mm.bing.net/th?id=OIP.qtq0E3ZWMOmUUVy0SrQe2QHaIq&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 7,
      title: "CARROM ",
      author: "BOARD AND COINS COMBO",
      price: 1693,
      img: "https://tse3.mm.bing.net/th?id=OIP.QwkjuNO4v1Jnp5nnQ128ewHaHr&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 8,
      title: "CHESS",
      author: "BOARD WITH COINS COMBO",
      price: 399,
      img: "https://i5.walmartimages.com/asr/15b0f85a-6e25-4d9b-820c-d1eeeea14a28_1.815bbb982480a1dd5bf94624549d46e3.jpeg?odnWidth=1000&odnHeight=1000&odnBg=ffffff",
      amount: 1,
    },
    {
      id: 9,
      title: "TENNIS",
      author:" BALL AND ROCKET COMBO",
      price: 899,
      img: "https://images.unsplash.com/photo-1602211844066-d3bb556e983b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3BvcnRzJTIwZXF1aXBtZW50fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      amount: 1,
    },
    {
      id: 10,
      title: "TABLE TENNIS",
      author: "ROCKET AND BALL COMBO",
      price: 889,
      img: "https://i5.walmartimages.com/asr/707d3c3f-fcfe-4d53-bbdb-f96957306df5.87344308e8307900320535948803e0ff.jpeg",
      amount: 1,
    },
    {
      id: 11,
      title: "ARCHERY",
      author: "COMBO",
      price: 3119,
      img: "https://m.media-amazon.com/images/I/51SVUUmaTdL.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "BADMINTON",
      author: "ROCKET WITH NYLON SHUTTLES",
      price: 2157,
      img: "https://tse3.mm.bing.net/th?id=OIP.S6s7I7rV7gXfHKVGEnMYEAHaHa&pid=Api&P=0&h=180",
      amount: 1,
    },
  ];
  
  export default list;